# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branc
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag name for image' 
        required: true
      namespace:
       description: 'namespace'
       required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      

      # Runs a single command using the runners shell
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        
      - name: Setup ECR
        run: |
          # Login to AWS ECR
          $( aws ecr get-login --no-include-email )
      - name: Build anddocker push $AWS_ACCOUNT_ID.dkr.ecr.aws-region.amazonaws.com/$CONTAINER_IMAGE tag the image
        run: |
          # Build and tag the image
          docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.aws-region.amazonaws.com/$CONTAINER_IMAGE ./app
           
    # Add additional steps here like scanning of image
      - name: push
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.aws-region.amazonaws.com/$CONTAINER_IMAGE
