name: Deploy to ECR

on:
  pull_request:
    branches:
      - main
    types: [closed]
 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag name for image' 
        required: true
      namespace:
       description: 'namespace'
       required: true

jobs:
  
  build:
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: automation
        IMAGE_TAG:  "Tags: ${{ github.event.inputs.tags }}"
      run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tags }} .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tags }}

    
